"""empty message

Revision ID: ead679bceca8
Revises: 9b0024a67600
Create Date: 2022-05-04 15:32:22.424309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead679bceca8'
down_revision = '9b0024a67600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user-points', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user-points', 'notes')
    # ### end Alembic commands ###
